/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author SAIF FATIH D
 */
public class absen extends javax.swing.JInternalFrame {
private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private String sql;
    /**
     * Creates new form absen
     */
    public absen() {
        initComponents();
        kosong();
        datatable();
        rdgroup.add(rhadir);
        rdgroup.add(rnhadir);
        
    }
    
    protected void kosong(){
        labnip.setText("");
        labnama.setText("");
        labtelp.setText("");
        rdgroup.clearSelection();
    }
    
protected void datatable(){
    // Menyesuaikan isi header tabel dengan data yang dipanggil (NIP, Nama, No Telp, Tgl, Kehadiran, Keterangan)
    Object[] Baris = {"ID Admin", "Nama Admin", "No. Telepon", "Tanggal", "Kehadiran", "Keterangan"};
    tabmode = new DefaultTableModel(null, Baris);
    tblabsn.setModel(tabmode); 

    try {
        // Pembenaran Query: Menggunakan LEFT JOIN agar data admin yang belum absen tetap muncul di tabel
        String sql = "SELECT a.kd_admin, a.nm_admin, a.no_telepon, b.tgl, b.kehadiran, b.keterangan " +
                     "FROM admin a " +
                     "LEFT JOIN absen_admin b ON a.kd_admin = b.kd_admin";

        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            // Mengambil data berdasarkan alias query yang benar
            tabmode.addRow(new Object[]{
                hasil.getString("kd_admin"),
                hasil.getString("nm_admin"),
                hasil.getString("no_telepon"),                     // Menampilkan No Telepon di tabel
                hasil.getString("tgl") == null ? "-" : hasil.getString("tgl"), // Jika belum absen, tulis "-"
                hasil.getString("kehadiran") == null ? "-" : hasil.getString("kehadiran"),
                hasil.getString("keterangan") == null ? "-" : hasil.getString("keterangan")
            });
        }
    } catch (Exception e){
        JOptionPane.showMessageDialog(null,"data gagal dipanggil: " + e.getMessage());
    }
}        
        
        
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labnip = new javax.swing.JLabel();
        labnama = new javax.swing.JLabel();
        labtelp = new javax.swing.JLabel();
        rhadir = new javax.swing.JRadioButton();
        rnhadir = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txttidakhadir = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        txtcariabsen = new javax.swing.JTextField();
        bcariabsen = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bcariadmin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblabsn = new javax.swing.JTable();

        setBackground(new java.awt.Color(252, 249, 235));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("ABSEN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("No.Telpon");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Kehadiran");

        labnip.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labnip.setText("jLabel6");

        labnama.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labnama.setText("jLabel7");

        labtelp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labtelp.setText("jLabel8");

        rhadir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rhadir.setText("Hadir");
        rhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhadirActionPerformed(evt);
            }
        });

        rnhadir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rnhadir.setText("Tidak Hadir");
        rnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnhadirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Data Absen");

        txttidakhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttidakhadirActionPerformed(evt);
            }
        });

        bsimpan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bbatal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        txtcariabsen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariabsenKeyPressed(evt);
            }
        });

        bcariabsen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bcariabsen.setText("Cari");
        bcariabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariabsenActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Keterangan");

        bcariadmin.setText("Cari");
        bcariadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariadminActionPerformed(evt);
            }
        });

        tblabsn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblabsn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rhadir)
                            .addComponent(labtelp)
                            .addComponent(labnama)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labnip)
                                .addGap(31, 31, 31)
                                .addComponent(bcariadmin))
                            .addComponent(rnhadir)
                            .addComponent(txttidakhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcariabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bcariabsen))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(291, 291, 291))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labnip)
                    .addComponent(txtcariabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcariabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcariadmin))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labnama))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labtelp))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rhadir))
                        .addGap(14, 14, 14)
                        .addComponent(rnhadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttidakhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnhadirActionPerformed
txttidakhadir.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rnhadirActionPerformed

    private void txttidakhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttidakhadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttidakhadirActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
try {
        String nip = labnip.getText();
        String kehadiran = rhadir.isSelected() ? "Hadir" : "Tidak Hadir";
        String keterangan = txttidakhadir.getText();
        java.sql.Date tanggalSekarang = new java.sql.Date(System.currentTimeMillis());

        // Query INSERT ke tabel absen_admin
        String sql = "INSERT INTO absen_admin (kd_admin, tgl, kehadiran, keterangan) VALUES (?, ?, ?, ?)";

        java.sql.PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, nip);
        stat.setDate(2, tanggalSekarang);
        stat.setString(3, kehadiran);
        stat.setString(4, keterangan);

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Absen Berhasil Disimpan!");

        // Panggil method untuk refresh tabel riwayat/view
        datatable(); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan: " + e.getMessage());
    }

    }//GEN-LAST:event_bsimpanActionPerformed

    private void rhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhadirActionPerformed
    txttidakhadir.setEnabled(false);
    }//GEN-LAST:event_rhadirActionPerformed

    private void txtcariabsenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariabsenKeyPressed
if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            datatable();
        }      // TODO a        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariabsenKeyPressed

    private void bcariabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariabsenActionPerformed
datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bcariabsenActionPerformed

    private void bcariadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariadminActionPerformed
        popup_admin pop = new popup_admin(null, true);
    // Mengaitkan form absen saat ini ke dalam variabel pop-up
    pop.fAbsen = this;
    pop.setVisible(true);
    pop.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bcariadminActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
    datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcariabsen;
    private javax.swing.JButton bcariadmin;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labnama;
    public javax.swing.JLabel labnip;
    public javax.swing.JLabel labtelp;
    private javax.swing.ButtonGroup rdgroup;
    private javax.swing.JRadioButton rhadir;
    private javax.swing.JRadioButton rnhadir;
    private javax.swing.JTable tblabsn;
    private javax.swing.JTextField txtcariabsen;
    private javax.swing.JTextField txttidakhadir;
    // End of variables declaration//GEN-END:variables
}
