/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.awt.Image;
import static java.awt.SystemColor.desktop;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import koneksi.koneksi;
import java.awt.Frame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.Color;

/**
 *
 * @author User
 */
public class dashboard_utama extends javax.swing.JFrame {

    
    
    public dashboard_utama() {
        initComponents();               
        
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
       
        tampilkanhalaman_utama();
    }
    
        // 2. Method bukaForm (Mesin utama Anda)
    private void bukaForm(javax.swing.JInternalFrame f) {
        desktop.removeAll();
        desktop.repaint();
        desktop.add(f);
        f.setVisible(true);

        // Menghilangkan title bar
        BasicInternalFrameUI ui = (BasicInternalFrameUI) f.getUI();
        ui.setNorthPane(null);

        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }
        
        private void tampilkanhalaman_utama() {
        // Karena nama variabel Anda sudah "desktop", gunakan nama ini:
        desktop.removeAll(); 
        desktop.repaint();
         
        halaman_utama home = new halaman_utama();
        desktop.add(home);
        home.setVisible(true);
        
        try {
            home.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
        
        
                   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanelKiri = new javax.swing.JPanel();
        bhome = new javax.swing.JButton();
        bpemohon = new javax.swing.JButton();
        babsen = new javax.swing.JButton();
        btanah = new javax.swing.JButton();
        bjadwal = new javax.swing.JButton();
        bprmhnan = new javax.swing.JButton();
        bpenugasan = new javax.swing.JButton();
        btugas = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        badmin = new javax.swing.JButton();
        sidebarPanelAtas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanelKiri.setBackground(new java.awt.Color(0, 51, 102));

        bhome.setBackground(new java.awt.Color(0, 51, 102));
        bhome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bhome.setForeground(new java.awt.Color(255, 255, 255));
        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/beranda.png"))); // NOI18N
        bhome.setText("Beranda");
        bhome.setBorderPainted(false);
        bhome.setContentAreaFilled(false);
        bhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhome.setOpaque(true);
        bhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhomeMouseExited(evt);
            }
        });
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        bpemohon.setBackground(new java.awt.Color(0, 51, 102));
        bpemohon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bpemohon.setForeground(new java.awt.Color(255, 255, 255));
        bpemohon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/pemohon.png"))); // NOI18N
        bpemohon.setText("Pemohon");
        bpemohon.setBorderPainted(false);
        bpemohon.setContentAreaFilled(false);
        bpemohon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpemohon.setOpaque(true);
        bpemohon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpemohonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpemohonMouseExited(evt);
            }
        });
        bpemohon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemohonActionPerformed(evt);
            }
        });

        babsen.setBackground(new java.awt.Color(0, 51, 102));
        babsen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        babsen.setForeground(new java.awt.Color(255, 255, 255));
        babsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/absen.png"))); // NOI18N
        babsen.setText("Absen");
        babsen.setBorderPainted(false);
        babsen.setContentAreaFilled(false);
        babsen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        babsen.setOpaque(true);
        babsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                babsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                babsenMouseExited(evt);
            }
        });
        babsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                babsenActionPerformed(evt);
            }
        });

        btanah.setBackground(new java.awt.Color(0, 51, 102));
        btanah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btanah.setForeground(new java.awt.Color(255, 255, 255));
        btanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/tanah.png"))); // NOI18N
        btanah.setText("Tanah");
        btanah.setBorderPainted(false);
        btanah.setContentAreaFilled(false);
        btanah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btanah.setOpaque(true);
        btanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btanahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btanahMouseExited(evt);
            }
        });
        btanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanahActionPerformed(evt);
            }
        });

        bjadwal.setBackground(new java.awt.Color(0, 51, 102));
        bjadwal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bjadwal.setForeground(new java.awt.Color(255, 255, 255));
        bjadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/jadwal.png"))); // NOI18N
        bjadwal.setText("Jadwal");
        bjadwal.setBorderPainted(false);
        bjadwal.setContentAreaFilled(false);
        bjadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bjadwal.setOpaque(true);
        bjadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bjadwalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bjadwalMouseExited(evt);
            }
        });
        bjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjadwalActionPerformed(evt);
            }
        });

        bprmhnan.setBackground(new java.awt.Color(0, 51, 102));
        bprmhnan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bprmhnan.setForeground(new java.awt.Color(255, 255, 255));
        bprmhnan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/permohonan.png"))); // NOI18N
        bprmhnan.setText("Permohonan");
        bprmhnan.setBorderPainted(false);
        bprmhnan.setContentAreaFilled(false);
        bprmhnan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bprmhnan.setOpaque(true);
        bprmhnan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bprmhnanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bprmhnanMouseExited(evt);
            }
        });
        bprmhnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprmhnanActionPerformed(evt);
            }
        });

        bpenugasan.setBackground(new java.awt.Color(0, 51, 102));
        bpenugasan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bpenugasan.setForeground(new java.awt.Color(255, 255, 255));
        bpenugasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/delegation.png"))); // NOI18N
        bpenugasan.setText("Penugasan");
        bpenugasan.setBorderPainted(false);
        bpenugasan.setContentAreaFilled(false);
        bpenugasan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpenugasan.setOpaque(true);
        bpenugasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpenugasanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpenugasanMouseExited(evt);
            }
        });
        bpenugasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpenugasanActionPerformed(evt);
            }
        });

        btugas.setBackground(new java.awt.Color(0, 51, 102));
        btugas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btugas.setForeground(new java.awt.Color(255, 255, 255));
        btugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/tugas.png"))); // NOI18N
        btugas.setText("Tugas");
        btugas.setBorderPainted(false);
        btugas.setContentAreaFilled(false);
        btugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btugas.setOpaque(true);
        btugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btugasMouseExited(evt);
            }
        });
        btugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btugasActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(0, 51, 102));
        bkeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bkeluar.setForeground(new java.awt.Color(255, 255, 255));
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/logout.png"))); // NOI18N
        bkeluar.setText("Logout");
        bkeluar.setBorderPainted(false);
        bkeluar.setContentAreaFilled(false);
        bkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeluar.setFocusPainted(false);
        bkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bkeluar.setOpaque(true);
        bkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bkeluarMouseExited(evt);
            }
        });
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        badmin.setBackground(new java.awt.Color(0, 51, 102));
        badmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        badmin.setForeground(new java.awt.Color(255, 255, 255));
        badmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/admin.png"))); // NOI18N
        badmin.setText("Admin");
        badmin.setBorderPainted(false);
        badmin.setContentAreaFilled(false);
        badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        badmin.setOpaque(true);
        badmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                badminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                badminMouseExited(evt);
            }
        });
        badmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelKiriLayout = new javax.swing.GroupLayout(sidebarPanelKiri);
        sidebarPanelKiri.setLayout(sidebarPanelKiriLayout);
        sidebarPanelKiriLayout.setHorizontalGroup(
            sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelKiriLayout.createSequentialGroup()
                .addGroup(sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bprmhnan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bhome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(badmin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(babsen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bpemohon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btanah, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btugas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bjadwal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bkeluar)
                        .addComponent(bpenugasan)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        sidebarPanelKiriLayout.setVerticalGroup(
            sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelKiriLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(bhome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(babsen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpemohon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btanah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bprmhnan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bjadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpenugasan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(bkeluar)
                .addGap(36, 36, 36))
        );

        getContentPane().add(sidebarPanelKiri, java.awt.BorderLayout.LINE_START);

        sidebarPanelAtas.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/panel atas.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sidebarPanelAtasLayout = new javax.swing.GroupLayout(sidebarPanelAtas);
        sidebarPanelAtas.setLayout(sidebarPanelAtasLayout);
        sidebarPanelAtasLayout.setHorizontalGroup(
            sidebarPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelAtasLayout.setVerticalGroup(
            sidebarPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(sidebarPanelAtas, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1719, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("© 2024 BPN Jakarta Timur. All rights reserved.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Melayani, Profesional, Terpercaya");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1222, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void babsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_babsenActionPerformed
     bukaForm(new absen());
    }//GEN-LAST:event_babsenActionPerformed

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
    bukaForm(new halaman_utama());
    }//GEN-LAST:event_bhomeActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
    
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
              "Apakah Anda yakin ingin keluar dari aplikasi?", 
              "Konfirmasi Keluar", 
              javax.swing.JOptionPane.YES_NO_OPTION);

        //Jika pengguna memilih "Yes"
           if (confirm == javax.swing.JOptionPane.YES_OPTION) {
               
        //Panggil form login 
           login login= new login();
           login.setVisible(true);
    
         //Tutup dashboard
           this.dispose();
    }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void btanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanahActionPerformed
    bukaForm(new tanah());
    }//GEN-LAST:event_btanahActionPerformed

    private void bprmhnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprmhnanActionPerformed
    bukaForm(new permohonan());
    }//GEN-LAST:event_bprmhnanActionPerformed

    private void bpemohonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemohonActionPerformed
    bukaForm(new pemohon());
    }//GEN-LAST:event_bpemohonActionPerformed

    private void bjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjadwalActionPerformed
    bukaForm(new jadwal());
    }//GEN-LAST:event_bjadwalActionPerformed

    private void btugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btugasActionPerformed
    bukaForm(new tugas());
    }//GEN-LAST:event_btugasActionPerformed

    private void bpenugasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpenugasanActionPerformed
    bukaForm(new penugasan());
    }//GEN-LAST:event_bpenugasanActionPerformed

    private void bkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseEntered
          bkeluar.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bkeluarMouseEntered

    private void bkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseExited
        bkeluar.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bkeluarMouseExited

    private void bpenugasanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpenugasanMouseEntered
        bpenugasan.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bpenugasanMouseEntered

    private void bpenugasanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpenugasanMouseExited
        bpenugasan.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bpenugasanMouseExited

    private void btugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btugasMouseEntered
        btugas.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_btugasMouseEntered

    private void btugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btugasMouseExited
        btugas.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_btugasMouseExited

    private void bjadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bjadwalMouseEntered
        bjadwal.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bjadwalMouseEntered

    private void bjadwalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bjadwalMouseExited
        bjadwal.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bjadwalMouseExited

    private void btanahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btanahMouseEntered
       btanah.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_btanahMouseEntered

    private void btanahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btanahMouseExited
        btanah.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_btanahMouseExited

    private void bpemohonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpemohonMouseEntered
        bpemohon.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bpemohonMouseEntered

    private void bpemohonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpemohonMouseExited
        bpemohon.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bpemohonMouseExited

    private void bprmhnanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bprmhnanMouseEntered
        bprmhnan.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bprmhnanMouseEntered

    private void bprmhnanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bprmhnanMouseExited
        bprmhnan.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bprmhnanMouseExited

    private void bhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhomeMouseEntered
        bhome.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bhomeMouseEntered

    private void bhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhomeMouseExited
        bhome.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bhomeMouseExited

    private void babsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_babsenMouseEntered
        babsen.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_babsenMouseEntered

    private void babsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_babsenMouseExited
        babsen.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_babsenMouseExited

    private void badminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminMouseEntered
         badmin.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_badminMouseEntered

    private void badminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminMouseExited
        badmin.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_badminMouseExited

    private void badminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badminActionPerformed

    private void badminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminMouseClicked
        bukaForm(new admin());
    }//GEN-LAST:event_badminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_utama().setVisible(true);
            }
        });
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babsen;
    private javax.swing.JButton badmin;
    private javax.swing.JButton bhome;
    private javax.swing.JButton bjadwal;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bpemohon;
    private javax.swing.JButton bpenugasan;
    private javax.swing.JButton bprmhnan;
    private javax.swing.JButton btanah;
    private javax.swing.JButton btugas;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sidebarPanelAtas;
    private javax.swing.JPanel sidebarPanelKiri;
    // End of variables declaration//GEN-END:variables
}
