/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.awt.Image;
import static java.awt.SystemColor.desktop;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import koneksi.koneksi;
import java.awt.Frame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.Color;

/**
 *
 * @author User
 */
public class dashboard_utama extends javax.swing.JFrame {

    
    
    public dashboard_utama() {
        initComponents();               
        
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
       
        tampilkanhalaman_utama();
    }
    
        // 2. Method bukaForm (Mesin utama Anda)
    private void bukaForm(javax.swing.JInternalFrame f) {
        desktop.removeAll();
        desktop.repaint();
        desktop.add(f);
        f.setVisible(true);

        // Menghilangkan title bar
        BasicInternalFrameUI ui = (BasicInternalFrameUI) f.getUI();
        ui.setNorthPane(null);

        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }
        
        private void tampilkanhalaman_utama() {
        // Karena nama variabel Anda sudah "desktop", gunakan nama ini:
        desktop.removeAll(); 
        desktop.repaint();
         
        halaman_utama home = new halaman_utama();
        desktop.add(home);
        home.setVisible(true);
        
        try {
            home.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
        
        
                   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanelKiri = new javax.swing.JPanel();
        badmin = new javax.swing.JButton();
        babsen = new javax.swing.JButton();
        bpemohon = new javax.swing.JButton();
        btanah = new javax.swing.JButton();
        bjadwal = new javax.swing.JButton();
        bprmhnan = new javax.swing.JButton();
        bpenugasan = new javax.swing.JButton();
        btugas = new javax.swing.JButton();
        bhome = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        sidebarPanelAtas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanelKiri.setBackground(new java.awt.Color(0, 51, 102));

        badmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        badmin.setForeground(new java.awt.Color(255, 255, 255));
        badmin.setText("Admin");
        badmin.setBorderPainted(false);
        badmin.setContentAreaFilled(false);
        badmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminActionPerformed(evt);
            }
        });

        babsen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        babsen.setForeground(new java.awt.Color(255, 255, 255));
        babsen.setText("Absen");
        babsen.setBorderPainted(false);
        babsen.setContentAreaFilled(false);
        babsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                babsenActionPerformed(evt);
            }
        });

        bpemohon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bpemohon.setForeground(new java.awt.Color(255, 255, 255));
        bpemohon.setText("Pemohon");
        bpemohon.setBorderPainted(false);
        bpemohon.setContentAreaFilled(false);
        bpemohon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemohonActionPerformed(evt);
            }
        });

        btanah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btanah.setForeground(new java.awt.Color(255, 255, 255));
        btanah.setText("Tanah");
        btanah.setBorderPainted(false);
        btanah.setContentAreaFilled(false);
        btanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanahActionPerformed(evt);
            }
        });

        bjadwal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bjadwal.setForeground(new java.awt.Color(255, 255, 255));
        bjadwal.setText("Jadwal");
        bjadwal.setBorderPainted(false);
        bjadwal.setContentAreaFilled(false);
        bjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjadwalActionPerformed(evt);
            }
        });

        bprmhnan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bprmhnan.setForeground(new java.awt.Color(255, 255, 255));
        bprmhnan.setText("Permohonan");
        bprmhnan.setBorderPainted(false);
        bprmhnan.setContentAreaFilled(false);
        bprmhnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprmhnanActionPerformed(evt);
            }
        });

        bpenugasan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bpenugasan.setForeground(new java.awt.Color(255, 255, 255));
        bpenugasan.setText("Penugasan");
        bpenugasan.setBorderPainted(false);
        bpenugasan.setContentAreaFilled(false);
        bpenugasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpenugasanActionPerformed(evt);
            }
        });

        btugas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btugas.setForeground(new java.awt.Color(255, 255, 255));
        btugas.setText("Tugas");
        btugas.setBorderPainted(false);
        btugas.setContentAreaFilled(false);
        btugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btugasActionPerformed(evt);
            }
        });

        bhome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bhome.setForeground(new java.awt.Color(255, 255, 255));
        bhome.setText("Home");
        bhome.setBorderPainted(false);
        bhome.setContentAreaFilled(false);
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(0, 51, 102));
        bkeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bkeluar.setForeground(new java.awt.Color(255, 255, 255));
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/exit.png"))); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.setBorderPainted(false);
        bkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeluar.setFocusPainted(false);
        bkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bkeluarMouseExited(evt);
            }
        });
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelKiriLayout = new javax.swing.GroupLayout(sidebarPanelKiri);
        sidebarPanelKiri.setLayout(sidebarPanelKiriLayout);
        sidebarPanelKiriLayout.setHorizontalGroup(
            sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(badmin)
                    .addComponent(babsen)
                    .addComponent(bprmhnan)
                    .addComponent(bpemohon)
                    .addComponent(btanah)
                    .addComponent(bjadwal)
                    .addComponent(bpenugasan)
                    .addComponent(btugas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelKiriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bkeluar)
                .addGap(18, 18, 18)
                .addComponent(bhome)
                .addGap(17, 17, 17))
        );
        sidebarPanelKiriLayout.setVerticalGroup(
            sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelKiriLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(babsen)
                .addGap(18, 18, 18)
                .addComponent(badmin)
                .addGap(18, 18, 18)
                .addComponent(bprmhnan)
                .addGap(18, 18, 18)
                .addComponent(bpemohon)
                .addGap(18, 18, 18)
                .addComponent(btanah)
                .addGap(18, 18, 18)
                .addComponent(bjadwal)
                .addGap(18, 18, 18)
                .addComponent(btugas)
                .addGap(18, 18, 18)
                .addComponent(bpenugasan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(sidebarPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhome)
                    .addComponent(bkeluar))
                .addGap(52, 52, 52))
        );

        getContentPane().add(sidebarPanelKiri, java.awt.BorderLayout.LINE_START);

        sidebarPanelAtas.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/panel atas.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sidebarPanelAtasLayout = new javax.swing.GroupLayout(sidebarPanelAtas);
        sidebarPanelAtas.setLayout(sidebarPanelAtasLayout);
        sidebarPanelAtasLayout.setHorizontalGroup(
            sidebarPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        sidebarPanelAtasLayout.setVerticalGroup(
            sidebarPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(sidebarPanelAtas, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void babsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_babsenActionPerformed
     bukaForm(new absen());
    }//GEN-LAST:event_babsenActionPerformed

    private void badminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminActionPerformed
    bukaForm(new admin());
    }//GEN-LAST:event_badminActionPerformed

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
    bukaForm(new halaman_utama());
    }//GEN-LAST:event_bhomeActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
    
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
              "Apakah Anda yakin ingin keluar dari aplikasi?", 
              "Konfirmasi Keluar", 
              javax.swing.JOptionPane.YES_NO_OPTION);

        //Jika pengguna memilih "Yes"
           if (confirm == javax.swing.JOptionPane.YES_OPTION) {
               
        //Panggil form login 
           login login= new login();
           login.setVisible(true);
    
         //Tutup dashboard
           this.dispose();
    }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void btanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanahActionPerformed
    bukaForm(new tanah());
    }//GEN-LAST:event_btanahActionPerformed

    private void bprmhnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprmhnanActionPerformed
    bukaForm(new permohonan());
    }//GEN-LAST:event_bprmhnanActionPerformed

    private void bpemohonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemohonActionPerformed
    bukaForm(new pemohon());
    }//GEN-LAST:event_bpemohonActionPerformed

    private void bjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjadwalActionPerformed
    bukaForm(new jadwal());
    }//GEN-LAST:event_bjadwalActionPerformed

    private void btugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btugasActionPerformed
    bukaForm(new tugas());
    }//GEN-LAST:event_btugasActionPerformed

    private void bpenugasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpenugasanActionPerformed
    bukaForm(new penugasan());
    }//GEN-LAST:event_bpenugasanActionPerformed

    private void bkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseEntered
      bkeluar.setBackground(new Color(0, 80, 157));
    }//GEN-LAST:event_bkeluarMouseEntered

    private void bkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseExited
        bkeluar.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bkeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_utama().setVisible(true);
            }
        });
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babsen;
    private javax.swing.JButton badmin;
    private javax.swing.JButton bhome;
    private javax.swing.JButton bjadwal;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bpemohon;
    private javax.swing.JButton bpenugasan;
    private javax.swing.JButton bprmhnan;
    private javax.swing.JButton btanah;
    private javax.swing.JButton btugas;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel sidebarPanelAtas;
    private javax.swing.JPanel sidebarPanelKiri;
    // End of variables declaration//GEN-END:variables
}
