/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ACER
 */
public class hasil extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    public String idPenugasanTerpilih, namaPemohonTerpilih, jenisLayananTerpilih, volumeTerpilih, lokasiTerpilih, hakTanahTerpilih, namaPetugasTerpilih, nipTerpilih, tanggalUkurTerpilih;
    
public void setPermohonanKeForm(){
        labidpngsn.setText(idPenugasanTerpilih);
        labnm.setText(namaPemohonTerpilih);
        labjl.setText(jenisLayananTerpilih);
        labvlm.setText(volumeTerpilih);
        lablks.setText(lokasiTerpilih);
        labhak.setText(hakTanahTerpilih);
        labnmptgs.setText(namaPetugasTerpilih);
        labnip.setText(nipTerpilih);
        labtggl.setText(tanggalUkurTerpilih);
    }
    /**
     * Creates new form hasil
     */
    public hasil() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }

    protected void aktif(){
        txtidhsl.requestFocus();
    }
    
    protected void kosong(){
        txtidhsl.setText("");
        labidpngsn.setText("");
        labnm.setText("");
        labjl.setText("");
        labvlm.setText("");
        lablks.setText("");
        labhak.setText("");
        labnmptgs.setText("");
        labnip.setText("");
        labtggl.setText("");
        cbprgs.setSelectedIndex(0);
        txthsl.setText("");
    }
    
    protected void datatable() {
    Object[] Baris = {
        "ID Hasil", "ID Penugasan", "Nama Pemohon", "Jenis Layanan",  
        "Volume Tanah", "Lokasi Tanah", "Hak Tanah", "Nama Petugas", "NIP", "Tanggal Ukur", 
        "Progres", "Hasil Ukur"
    };
    
    DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
    String cariitem = txtcari.getText(); 
    
    try {
        String sql = "SELECT * FROM hasil WHERE idhasil LIKE '%" + cariitem + "%' OR nmpmhn LIKE '%" + cariitem + "%'";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("idhasil"),     
                hasil.getString("idpngsn"),        
                hasil.getString("nmpmhn"),    
                hasil.getString("jns"),      
                hasil.getString("vlm"),
                hasil.getString("lks"),      
                hasil.getString("haktanah"),      
                hasil.getString("nmptgs"),      
                hasil.getString("nip"),         
                hasil.getString("tggl"),         
                hasil.getString("progres"),         
                hasil.getString("hslukur"),    
            });
        }
        tblhasil.setModel(tabmode); // Pastikan nama JTable Anda benar
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
    }
}
    
    public void cetak() {
        try{
            String path="./src/report/reportHasil.jasper";
            HashMap parameter = new HashMap();
            String hasil = txtidhsl.getText();
            parameter.put("idhasil", txtidhsl.getText());
            System.out.println(hasil);
            JasperPrint print = JasperFillManager.fillReport(path, parameter,conn);
            JasperViewer.viewReport(print, false);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Dokumen tidak ada" +ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidhsl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labidpngsn = new javax.swing.JLabel();
        poppenugasan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labnm = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labjl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labvlm = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lablks = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labhak = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labnmptgs = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labnip = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labtggl = new javax.swing.JLabel();
        txthsl = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbprgs = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Penugasan");

        labidpngsn.setText("jLabel2");

        poppenugasan.setText("Cari");
        poppenugasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poppenugasanActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Hasil");

        jLabel4.setText("Nama Pemohon");

        labnm.setText("jLabel5");

        jLabel6.setText("Jenis Layanan");

        labjl.setText("jLabel7");

        jLabel8.setText("Volume");

        labvlm.setText("jLabel9");

        jLabel10.setText("Lokasi Tanah");

        lablks.setText("jLabel11");

        jLabel12.setText("Hak Tanah");

        labhak.setText("jLabel13");

        jLabel14.setText("Nama Petugas");

        labnmptgs.setText("jLabel15");

        jLabel16.setText("NIP");

        labnip.setText("jLabel17");

        jLabel18.setText("Tanggal Ukur");

        labtggl.setText("jLabel19");

        jLabel20.setText("Hasil Ukur");

        cbprgs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Ukur", "Proses Ukur", "Selesai Ukur" }));
        cbprgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbprgsActionPerformed(evt);
            }
        });

        jLabel21.setText("Progres");

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhasil);

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel2.setText("Form Hasil");

        print.setText("Cetak");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthsl)
                            .addComponent(labtggl)
                            .addComponent(labnip)
                            .addComponent(labnmptgs)
                            .addComponent(labhak)
                            .addComponent(lablks)
                            .addComponent(labvlm)
                            .addComponent(labjl)
                            .addComponent(labnm)
                            .addComponent(txtidhsl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labidpngsn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(poppenugasan))
                            .addComponent(cbprgs, 0, 140, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(print)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidhsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(bsimpan))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(labidpngsn)
                                    .addComponent(poppenugasan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(labnm)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(bubah)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(labjl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bhapus)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labvlm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lablks)
                            .addComponent(bbatal))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(labhak))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(labnmptgs)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(print)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(labnip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(labtggl))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbprgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(txthsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        //if (cbprgs.getSelectedIndex() == 0){
          //  JOptionPane.showMessageDialog(null, "Pilih jenis dulu!");
            //return;}
        String sql = "INSERT INTO hasil (idhasil, idpngsn, nmpmhn, jns, vlm, lks, haktanah, nmptgs, nip, tggl, progres, hslukur)"
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        
        // PETAKKAN KOMPONEN UI SESUAI KOLOM SQL DI ATAS
        stat.setString(1, txtidhsl.getText());  // idpngsn
        stat.setString(2, labidpngsn.getText());       // tggl
        stat.setString(3, labnm.getText());        // idprmhnn
        stat.setString(4, labjl.getText());    // idjdwl
        stat.setString(5, labvlm.getText());     // idptgs
        stat.setString(6, lablks.getText());
        stat.setString(7, labhak.getText());      // nmpmhn
        stat.setString(8, labnmptgs.getText());      // notelp
        stat.setString(9, labnip.getText());    // alm
        stat.setString(10, labtggl.getText());    // lks
        stat.setString(11, cbprgs.getSelectedItem().toString());   // vlm
        stat.setString(12, txthsl.getText());   // haktanah
       
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        
        kosong();
        aktif();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "data gagal disimpan " + e);
    }
    datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        //if (cbprgs.getSelectedIndex() == 0){
        //JOptionPane.showMessageDialog(null, "Pilih progress dulu!");
        //return;
    //}
        try {
            String sql = "update hasil set  idpngsn=?, nmpmhn=?, jns=?, vlm=?, lks=?, haktanah=?, nmptgs=?, nip=?, tggl=?, progres=?, hslukur=? where idhasil = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            //stat.setString(1, txtidhsl.getText());
            stat.setString(1, labidpngsn.getText());
            stat.setString(2, labnm.getText());
            stat.setString(3, labjl.getText());
            stat.setString(4, labvlm.getText());
            stat.setString(5, lablks.getText());
            stat.setString(6, labhak.getText());
            stat.setString(7, labnmptgs.getText());
            stat.setString(8, labnip.getText());
            stat.setString(9,labtggl.getText());
            stat.setString(10, cbprgs.getSelectedItem().toString());
            stat.setString(11,txthsl.getText());
            stat.setString(12,txtidhsl.getText());
            int result = stat.executeUpdate();

            if(result > 0){
                JOptionPane.showMessageDialog(null, "data berhasil diubah");
            } else {
                JOptionPane.showMessageDialog(null, "data tidak ditemukan");
            }

            kosong();
            aktif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah " + e);
        }
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from hasil where idhasil ='" + txtidhsl.getText() + "'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                aktif();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus " + e);
            }
            datatable();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
       int bar = tblhasil.getSelectedRow();
    javax.swing.table.TableModel model = tblhasil.getModel();
    
    txtidhsl.setText(model.getValueAt(bar, 0).toString());  
    labidpngsn.setText(model.getValueAt(bar, 1).toString());       
    labnm.setText(model.getValueAt(bar, 2).toString());        
    labjl.setText(model.getValueAt(bar, 3).toString());    
    labvlm.setText(model.getValueAt(bar, 4).toString());  
    lablks.setText(model.getValueAt(bar, 5).toString());
    labhak.setText(model.getValueAt(bar, 6).toString());      
    labnmptgs.setText(model.getValueAt(bar, 7).toString());      
    labnip.setText(model.getValueAt(bar, 8).toString());    
    labtggl.setText(model.getValueAt(bar, 9).toString());    
    String progresValue = model.getValueAt(bar, 10).toString();
    cbprgs.setSelectedItem(progresValue);
    txthsl.setText(model.getValueAt(bar,11).toString());
    }//GEN-LAST:event_tblhasilMouseClicked

    private void poppenugasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poppenugasanActionPerformed
        popup_penugasan popup = new popup_penugasan(null, true);
                popup.formHasil = this;
                popup.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_poppenugasanActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
         if (evt.getKeyCode()== KeyEvent.VK_ENTER){
           datatable();
       }         // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyPressed

    private void cbprgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbprgsActionPerformed
    if (cbprgs.getSelectedItem().toString().equalsIgnoreCase("Belum Ukur")) {
        txthsl.setEnabled(false);
        txthsl.setText(""); // Menghapus tulisan jika ada isi sebelumnya
    } else if (cbprgs.getSelectedItem().toString().equalsIgnoreCase("Proses Ukur")) {
        txthsl.setEnabled(false);
        txthsl.setText("");
    }else {
        txthsl.setEnabled(true);
    }
    }//GEN-LAST:event_cbprgsActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        cetak();
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbprgs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labhak;
    public javax.swing.JLabel labidpngsn;
    public javax.swing.JLabel labjl;
    public javax.swing.JLabel lablks;
    public javax.swing.JLabel labnip;
    public javax.swing.JLabel labnm;
    public javax.swing.JLabel labnmptgs;
    public javax.swing.JLabel labtggl;
    public javax.swing.JLabel labvlm;
    private javax.swing.JButton poppenugasan;
    private javax.swing.JButton print;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthsl;
    private javax.swing.JTextField txtidhsl;
    // End of variables declaration//GEN-END:variables
}
