/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author LightDen69
 */
public class penugasan extends javax.swing.JInternalFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;

    public String idPermohonanTerpilih, namaPemohonTerpilih, noTelpTerpilih, alamatTerpilih, jenisLayananTerpilih, volumeTerpilih, lokasiTerpilih, hakTanahTerpilih;
    public String idJadwalTerpilih, tglJadwalTerpilih;
    public String idPetugasTerpilih, namaPetugasTerpilih, NIPTerpilih, noKontakTerpilih;
   
    public void setPermohonanKeForm(){
        labid.setText(idPermohonanTerpilih);
        labnama.setText(namaPemohonTerpilih);
        labtelp.setText(noTelpTerpilih);
        labalamat.setText(alamatTerpilih);
        labjl.setText(jenisLayananTerpilih);
        labvtanah.setText(lokasiTerpilih);
        lablokasi.setText(volumeTerpilih);
        labhtanah.setText(hakTanahTerpilih);
    }
    
    public void setJadwalKeForm(){
        labidjdwl.setText(idJadwalTerpilih);
        labtgl.setText(tglJadwalTerpilih);
    }
    
    public void setPetugasKeForm(){
        labidptg.setText(idPetugasTerpilih);
        labpetu.setText(namaPetugasTerpilih);
        labnip.setText(NIPTerpilih);
        labkontak.setText(noKontakTerpilih);
    }
    /**
     * Creates new form penugasan
     */
    public penugasan() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }

    protected void aktif(){
        idpenugasan.requestFocus();
    }
 protected void kosong(){
        idpenugasan.setText("");
        labid.setText("");
        labidptg.setText("");
        labnama.setText("");
        labtelp.setText("");
        labalamat.setText("");
        labjl.setText("");
        labvtanah.setText("");
        lablokasi.setText("");
        labhtanah.setText("");
        labidjdwl.setText("");
        labtgl.setText("");
        labidptg.setText("");
        labpetu.setText("");
        labnip.setText("");
        labkontak.setText("");
        txtcari.setText("");
    }
 protected void datatable() {
    Object[] Baris = {
        "ID Penugasan", "ID Permohonan", "Nama Pemohon", "No Telpon", "Alamat","Jenis Layanan",  
        "Volume Tanah", "Lokasi Tanah", "Hak Tanah", "ID Jadwal", "Tanggal", 
        "ID Petugas", "Nama Petugas", "NIP", "No. Kontak"
    };
    
    DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
    String cariitem = txtcari.getText(); 
    
    try {
        String sql = "SELECT * FROM penugasan WHERE idpngsn LIKE '%" + cariitem + "%' OR nmpmhn LIKE '%" + cariitem + "%'";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("idpngsn"),     // Kolom 1
                hasil.getString("idprmhnn"),        // Kolom 2
                hasil.getString("nmpmhn"),    // Kolom 3
                hasil.getString("notelp"),      // Kolom 4
                hasil.getString("alm"),
                hasil.getString("jns"),      // Kolom 5
                hasil.getString("lks"),      // Kolom 6
                hasil.getString("vlm"),      // Kolom 7
                hasil.getString("haktanah"),         // Kolom 8
                hasil.getString("idjdwl"),         // Kolom 9
                hasil.getString("tggl"),         // Kolom 10
                hasil.getString("idptgs"),    // Kolom 11
                hasil.getString("nmptgs"),      // Kolom 12
                hasil.getString("nip"),         // Kolom 13
                hasil.getString("notlp")        // Kolom 14
            });
        }
        tblpenugasan.setModel(tabmode); // Pastikan nama JTable Anda benar
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
    }
}
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bcari1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idpenugasan = new javax.swing.JTextField();
        bkeluar = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bcari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpenugasan = new javax.swing.JTable();
        poppemohon = new javax.swing.JButton();
        poppetugas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labtelp = new javax.swing.JLabel();
        labalamat = new javax.swing.JLabel();
        lablokasi = new javax.swing.JLabel();
        labvtanah = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labhtanah = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labpetu = new javax.swing.JLabel();
        labnip = new javax.swing.JLabel();
        labkontak = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        labtgl = new javax.swing.JLabel();
        popjadwal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labnama = new javax.swing.JLabel();
        labidjdwl = new javax.swing.JLabel();
        labidptg = new javax.swing.JLabel();
        labid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labjl = new javax.swing.JLabel();

        bcari1.setText("Cari");
        bcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari1ActionPerformed(evt);
            }
        });
        bcari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bcari1KeyPressed(evt);
            }
        });

        setBackground(new java.awt.Color(252, 249, 235));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("PENUGASAN");

        jLabel2.setText("ID Penugasan");

        jLabel4.setText("ID Permohonan");

        jLabel5.setText("ID Petugas");

        idpenugasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpenugasanActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        breset.setBackground(new java.awt.Color(255, 255, 255));
        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cari Penugasan :");

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        bcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bcariKeyPressed(evt);
            }
        });

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        tblpenugasan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpenugasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenugasanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpenugasan);

        poppemohon.setText("Cari");
        poppemohon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poppemohonActionPerformed(evt);
            }
        });
        poppemohon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                poppemohonKeyPressed(evt);
            }
        });

        poppetugas.setText("Cari");
        poppetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poppetugasActionPerformed(evt);
            }
        });
        poppetugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                poppetugasKeyPressed(evt);
            }
        });

        jLabel7.setText("No. Telepon");

        jLabel8.setText("Alamat");

        jLabel10.setText("Lokasi");

        jLabel3.setText("Volume Tanah");

        labtelp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labtelp.setText("jLabel11");

        labalamat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labalamat.setText("jLabel12");

        lablokasi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lablokasi.setText("jLabel14");

        labvtanah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labvtanah.setText("jLabel15");

        jLabel18.setText("Hak Tanah");

        labhtanah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labhtanah.setText("jLabel19");

        jLabel20.setText("Nama Petugas");

        jLabel21.setText("NIP");

        jLabel22.setText("No Kontak");

        labpetu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labpetu.setText("jLabel23");

        labnip.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labnip.setText("jLabel24");

        labkontak.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labkontak.setText("jLabel25");

        jLabel26.setText("ID Jadwal");

        jLabel27.setText("Tgl Jadwal");

        labtgl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labtgl.setText("jLabel28");

        popjadwal.setText("Cari");
        popjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popjadwalActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Pemohon");

        labnama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labnama.setText("jLabel12");

        labidjdwl.setText("jLabel9");

        labidptg.setText("jLabel12");

        labid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labid.setText("jLabel9");

        jLabel9.setText("Jenis Layanan");

        labjl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labjl.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(poppemohon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idpenugasan, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(365, 365, 365)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(632, 632, 632)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(72, 72, 72)
                                                        .addComponent(labtelp))
                                                    .addComponent(jLabel8)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(185, 185, 185)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(labid)
                                                            .addComponent(labnama)
                                                            .addComponent(labjl)
                                                            .addComponent(labalamat)
                                                            .addComponent(labvtanah)
                                                            .addComponent(lablokasi)
                                                            .addComponent(labhtanah))))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(332, 332, 332)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel22))
                                                .addGap(120, 120, 120)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labnip)
                                                    .addComponent(labpetu)
                                                    .addComponent(labtgl)
                                                    .addComponent(labkontak)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(labidjdwl)
                                                            .addComponent(labidptg))
                                                        .addGap(134, 134, 134)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(poppetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(popjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(692, 692, 692)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(labpetu)
                            .addComponent(jLabel7)
                            .addComponent(labtelp)
                            .addComponent(bsimpan)
                            .addComponent(breset))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(labnip))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idpenugasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(poppemohon)
                                    .addComponent(labid)
                                    .addComponent(jLabel26)
                                    .addComponent(labidjdwl)
                                    .addComponent(popjadwal)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(labnama)
                                    .addComponent(jLabel27)
                                    .addComponent(labtgl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labidptg)
                            .addComponent(poppetugas))
                        .addGap(102, 102, 102)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(labalamat))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bubah)
                                    .addComponent(bhapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labjl))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labvtanah)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(labkontak))
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lablokasi))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(labhtanah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bkeluar)))
                .addGap(243, 243, 243))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void idpenugasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpenugasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpenugasanActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bresetActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "INSERT INTO penugasan (idpngsn, idprmhnn, nmpmhn, notelp, alm, jns, vlm, lks, haktanah, idjdwl, tggl, idptgs, nmptgs, nip, notlp)"
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
    
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        
        // PETAKKAN KOMPONEN UI SESUAI KOLOM SQL DI ATAS
        stat.setString(1, idpenugasan.getText());  // idpngsn
        stat.setString(2, labid.getText());       // tggl
        stat.setString(3, labnama.getText());        // idprmhnn
        stat.setString(4, labtelp.getText());    // idjdwl
        stat.setString(5, labalamat.getText());     // idptgs
        stat.setString(6, labjl.getText());
        stat.setString(7, labvtanah.getText());      // nmpmhn
        stat.setString(8, lablokasi.getText());      // notelp
        stat.setString(9, labhtanah.getText());    // alm
        stat.setString(10, labidjdwl.getText());    // lks
        stat.setString(11, labtgl.getText());   // vlm
        stat.setString(12, labidptg.getText());   // haktanah
        stat.setString(13, labpetu.getText());     // nmptgs
        stat.setString(14, labnip.getText());      // nip
        stat.setString(15, labkontak.getText());   // notlp
        
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        
        kosong();
        aktif();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "data gagal disimpan " + e);
    }
    datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try {
            String sql = "update penugasan set idpngsn=?, idprmhnn=?, nmpmhn=?, notelp=?, alm=?, jns=?, vlm=?, lks=?, haktanah=?, idjdwl=?, tggl=?, idptgs=?, nmptgs=?, nip=?, notlp=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            stat.setString(1, idpenugasan.getText());
            stat.setString(2, labid.getText());
            stat.setString(3, labnama.getText());
            stat.setString(4, labtelp.getText());
            stat.setString(5, labalamat.getText());
            stat.setString(6, labjl.getText());
            stat.setString(7, labvtanah.getText());
            stat.setString(8, lablokasi.getText());
            stat.setString(9, labhtanah.getText());
            stat.setString(10,labidjdwl.getText());
            stat.setString(11,labtgl.getText());
            stat.setString(12,labidptg.getText());
            stat.setString(13,labpetu.getText());
            stat.setString(14,labnip.getText());
            stat.setString(15,labkontak.getText());
            
            int result = stat.executeUpdate();

            if(result > 0){
                JOptionPane.showMessageDialog(null, "data berhasil diubah");
            } else {
                JOptionPane.showMessageDialog(null, "data tidak ditemukan");
            }

            kosong();
            aktif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah " + e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from penugasan where idpngsn ='" + idpenugasan.getText() + "'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                aktif();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus " + e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariKeyPressed

    private void tblpenugasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpenugasanMouseClicked
int bar = tblpenugasan.getSelectedRow();
    javax.swing.table.TableModel model = tblpenugasan.getModel();
    
    idpenugasan.setText(model.getValueAt(bar, 0).toString());  
    labid.setText(model.getValueAt(bar, 1).toString());       
    labnama.setText(model.getValueAt(bar, 2).toString());        
    labtelp.setText(model.getValueAt(bar, 3).toString());    
    labalamat.setText(model.getValueAt(bar, 4).toString());  
    labjl.setText(model.getValueAt(bar, 5).toString());
    labvtanah.setText(model.getValueAt(bar, 6).toString());      
    lablokasi.setText(model.getValueAt(bar, 7).toString());      
    labhtanah.setText(model.getValueAt(bar, 8).toString());    
    labidjdwl.setText(model.getValueAt(bar, 9).toString());    
    labtgl.setText(model.getValueAt(bar, 10).toString());    
    labidptg.setText(model.getValueAt(bar, 11).toString());   
    labpetu.setText(model.getValueAt(bar, 12).toString());     
    labnip.setText(model.getValueAt(bar, 13).toString());      
    labkontak.setText(model.getValueAt(bar, 14).toString());
    }//GEN-LAST:event_tblpenugasanMouseClicked

    private void bcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari1ActionPerformed
        datatable(); 
    }//GEN-LAST:event_bcari1ActionPerformed

    private void bcari1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcari1KeyPressed
        
    }//GEN-LAST:event_bcari1KeyPressed

    private void poppemohonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poppemohonActionPerformed
popup_permohonan popup = new popup_permohonan(null, true);
                popup.formPenugasan = this;
                popup.setVisible(true);
       
    }//GEN-LAST:event_poppemohonActionPerformed

    private void poppemohonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poppemohonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_poppemohonKeyPressed

    private void poppetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poppetugasActionPerformed
popup_tugas popup = new popup_tugas(null, true);
                popup.formPenugasan = this;
                popup.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_poppetugasActionPerformed

    private void poppetugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poppetugasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_poppetugasKeyPressed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
         if (evt.getKeyCode()== KeyEvent.VK_ENTER){
           datatable();
       }   
    }//GEN-LAST:event_txtcariKeyPressed

    private void popjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popjadwalActionPerformed
        popup_jadwal popup = new popup_jadwal(null, true);
                popup.formPenugasan = this;
                popup.setVisible(true);
    }//GEN-LAST:event_popjadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penugasan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penugasan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penugasan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penugasan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penugasan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcari1;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JTextField idpenugasan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labalamat;
    public javax.swing.JLabel labhtanah;
    public javax.swing.JLabel labid;
    public javax.swing.JLabel labidjdwl;
    public javax.swing.JLabel labidptg;
    public javax.swing.JLabel labjl;
    public javax.swing.JLabel labkontak;
    public javax.swing.JLabel lablokasi;
    public javax.swing.JLabel labnama;
    public javax.swing.JLabel labnip;
    public javax.swing.JLabel labpetu;
    public javax.swing.JLabel labtelp;
    public javax.swing.JLabel labtgl;
    public javax.swing.JLabel labvtanah;
    private javax.swing.JButton popjadwal;
    private javax.swing.JButton poppemohon;
    private javax.swing.JButton poppetugas;
    private javax.swing.JTable tblpenugasan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
