/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author ADVAN
 */
public class permohonan extends javax.swing.JInternalFrame {
 private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public String idPemohonTerpilih;
    public String namaPemohonTerpilih;
    public String alamatPemohonTerpilih;
    public String telpPemohonTerpilih;
    public String idTanahTerpilih, lokasiTerpilih, volumeTerpilih, hakTerpilih;
    /**
     * Creates new form tugas
     */
    public void setPemohonKeForm(){
        labid.setText(idPemohonTerpilih);
        labnm.setText(namaPemohonTerpilih);
        labalm.setText(alamatPemohonTerpilih);
        labtelp.setText(telpPemohonTerpilih);
    }
    
    public void setTanahKeForm(){
    labidtnh.setText(idTanahTerpilih);
    lablks.setText(lokasiTerpilih);
    labvlm.setText(volumeTerpilih);
    labhak.setText(hakTerpilih);
}
    public permohonan() {
        initComponents();
        boxjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Jenis Layanan",
        "Pengukuran dan Pemetaan kadastral",
        "penggabungan Bidang",
        "Pemisahan Bidang",
        "Penataan Batas"
    }));
        kosong();
        aktif();
        datatable();
    }
    
        protected void aktif(){
        txtidpermohonan.requestFocus();
    }

    protected void kosong(){
        txtidpermohonan.setText("");
        tgl.setDate(null);
        boxjenis.setSelectedIndex(0);
        labid.setText("");
        labnm.setText("");
        labalm.setText("");
        labtelp.setText("");
        labidtnh.setText("");
        lablks.setText("");
        labvlm.setText("");
        labhak.setText("");
    }

    protected void datatable(){
    Object[] Baris = {"ID Permohonan", "Tgl Permohonan", "Jenis Layanan", "ID Pemohon","Nama Pemohon", "Alamat", "No. Telepon", "ID Tanah", "Lokasi", "Volome", "Hak"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem = jTextField5.getText();
     try {
        String sql = "SELECT * FROM permohonan where idprmhnn like '%" + cariitem +
                "%' or idpmhn like '%" + cariitem + "%' order by idprmhnn asc";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8),
                hasil.getString(9),
                hasil.getString(10),
                hasil.getString(11)
            });
        }
        tblpermohonan.setModel(tabmode);
     }catch (Exception e){
         JOptionPane.showMessageDialog(null,"data gagal di panggil" +e);
     }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidpermohonan = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpermohonan = new javax.swing.JTable();
        boxjenis = new javax.swing.JComboBox<>();
        tgl = new com.toedter.calendar.JDateChooser();
        bcari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labnm = new javax.swing.JLabel();
        labalm = new javax.swing.JLabel();
        labtelp = new javax.swing.JLabel();
        labidtnh = new javax.swing.JLabel();
        lablks = new javax.swing.JLabel();
        labvlm = new javax.swing.JLabel();
        labhak = new javax.swing.JLabel();
        bcariid = new javax.swing.JButton();
        bcariidtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("FORM PERMOHONAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID Permohonan");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tgl Permohonan");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Jenis Layanan");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("ID Pemohon");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ID Tanah");

        txtidpermohonan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpermohonanActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        tblpermohonan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpermohonan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpermohonanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpermohonan);

        boxjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Layanan" }));
        boxjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxjenisActionPerformed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        bcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bcariKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Nama Pemohon");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("No. Telp");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Lokasi");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Volume");

        labid.setText("jLabel2");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Hak");

        labnm.setText("jLabel6");

        labalm.setText("jLabel16");

        labtelp.setText("jLabel17");

        labidtnh.setText("jLabel18");

        lablks.setText("jLabel19");

        labvlm.setText("jLabel20");

        labhak.setText("jLabel21");

        bcariid.setText("Cari");
        bcariid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariidActionPerformed(evt);
            }
        });

        bcariidtn.setText("Cari");
        bcariidtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariidtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtidpermohonan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boxjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labid)
                                    .addGap(26, 26, 26)
                                    .addComponent(bcariid))
                                .addComponent(labnm)
                                .addComponent(labalm)
                                .addComponent(labtelp)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84)
                                                .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94)
                                                .addComponent(bcariidtn)))
                                        .addGap(67, 67, 67))
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lablks)
                                    .addComponent(labvlm)
                                    .addComponent(labhak)
                                    .addComponent(labidtnh))
                                .addGap(71, 71, 71)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtidpermohonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsimpan)
                            .addComponent(bhapus))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bubah)
                                .addComponent(breset)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(boxjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labidtnh)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcariidtn))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lablks))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(labvlm))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(labhak))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labid)
                    .addComponent(bcariid))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labnm))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labalm))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labtelp))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(bkeluar)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidpermohonanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpermohonanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpermohonanActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
    String sql = "insert into permohonan (idprmhnn, tggl, jns, idpmhn, nmpmhn, alm, notelp, idtnh, lks, vlm, haktanah) values (?,?,?,?,?,?,?,?,?,?,?)";
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtidpermohonan.getText());
        stat.setString(2, sdf.format(tgl.getDate()));
        stat.setString(3, boxjenis.getSelectedItem().toString());
        stat.setString(4, labid.getText());     // ID Pemohon
        stat.setString(5, labnm.getText());
        stat.setString(6, labalm.getText());
        stat.setString(7, labtelp.getText());
        stat.setString(8, labidtnh.getText());
        stat.setString(9, lablks.getText());
        stat.setString(10, labvlm.getText());     // MENGAMBIL NAMA PEMOHON DARI LABNM
        stat.setString(11, labhak.getText());  // ID Tanah
        
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        kosong();
        aktif();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "data gagal disimpan " + e);
    }
    datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblpermohonanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpermohonanMouseClicked
        int bar = tblpermohonan.getSelectedRow();
        String a = String.valueOf(tabmode.getValueAt(bar, 0));
        String b = String.valueOf(tabmode.getValueAt(bar, 1));
        String c = String.valueOf(tabmode.getValueAt(bar, 2));
        String d = String.valueOf(tabmode.getValueAt(bar, 3));
        String e = String.valueOf(tabmode.getValueAt(bar, 4));
        String f = String.valueOf(tabmode.getValueAt(bar, 5));
        String g = String.valueOf(tabmode.getValueAt(bar, 6));
        String h = String.valueOf(tabmode.getValueAt(bar, 7));
        String i = String.valueOf(tabmode.getValueAt(bar, 8));
        String j = String.valueOf(tabmode.getValueAt(bar, 9));
        String k = String.valueOf(tabmode.getValueAt(bar, 10));

        txtidpermohonan.setText(a);
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date tanggal = sdf.parse(b);
            tgl.setDate(tanggal);
        } catch (Exception t) {
            tgl.setDate(null);
        }
        boxjenis.setSelectedItem(c);
        labid.setText(d);
        labnm.setText(e);
        labalm.setText(f);
        labtelp.setText(g);
        labidtnh.setText(h);
        lablks.setText(i);
        labvlm.setText(j);
        labhak.setText(k);
    }//GEN-LAST:event_tblpermohonanMouseClicked

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
        // Update mencakup id pemohon dan id tanah yang baru dipilih
        String sql = "update permohonan set tggl=?, jns=?, idpmhn=?, nmpmhn=?, alm=?, notelp=?, idtnh=?, lks=?, vlm=?, haktanah=? where idprmhnn=?";
        PreparedStatement stat = conn.prepareStatement(sql);
        if (tgl.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal belum dipilih!");
            return;
        }
        java.sql.Date sqlDate = new java.sql.Date(tgl.getDate().getTime());
        stat.setDate(1, sqlDate);
        stat.setString(2, boxjenis.getSelectedItem().toString());
        stat.setString(3, labid.getText());
        stat.setString(4, labnm.getText());
        stat.setString(5, labalm.getText());
        stat.setString(6, labtelp.getText());
        stat.setString(7, labidtnh.getText());
        stat.setString(8, lablks.getText());
        stat.setString(9, labvlm.getText());
        stat.setString(10, labhak.getText());
        stat.setString(11, txtidpermohonan.getText());
        
        int result = stat.executeUpdate();
        
        if(result > 0){
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
        } else {
            JOptionPane.showMessageDialog(null, "data tidak ditemukan");
        }
        
        kosong();
        aktif();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "data gagal diubah " + e);
    }
    datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
    int ok = JOptionPane.showConfirmDialog(null, "hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from permohonan where idprmhnn ='" + txtidpermohonan.getText() + "'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                aktif();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus " + e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bresetActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
       dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariKeyPressed

    private void boxjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxjenisActionPerformed

    private void bcariidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariidActionPerformed
    popup_pemohon pop = new popup_pemohon(null, true);
    pop.formPermohonan = this; // Menghubungkan form permohonan saat ini ke pop-up
    pop.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_bcariidActionPerformed

    private void bcariidtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariidtnActionPerformed
    popup_tanah pop = new popup_tanah(null, true);
    pop.formPermohonan = this;
    pop.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_bcariidtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new permohonan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcariid;
    private javax.swing.JButton bcariidtn;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JComboBox<String> boxjenis;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    public javax.swing.JLabel labalm;
    public javax.swing.JLabel labhak;
    public javax.swing.JLabel labid;
    public javax.swing.JLabel labidtnh;
    public javax.swing.JLabel lablks;
    public javax.swing.JLabel labnm;
    public javax.swing.JLabel labtelp;
    public javax.swing.JLabel labvlm;
    private javax.swing.JTable tblpermohonan;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField txtidpermohonan;
    // End of variables declaration//GEN-END:variables
}
