/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author ACER
 */
public class popup_tanah extends javax.swing.JDialog {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    // Variabel penghubung ke form permohonan utama
    public permohonan formPermohonan = null; 

    protected void datatable(){
        Object[] Baris = {"ID Tanah", "Lokasi", "Volume", "Hak"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText(); // Sesuaikan nama komponen JTextField cari Anda
        try {
            String sql = "SELECT * FROM tanah WHERE idtnh LIKE '%"+cariitem+"%' OR lks LIKE '%"+cariitem+"%'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("idtnh"), // Sesuaikan nama kolom DB Anda
                    hasil.getString("lks"),
                    hasil.getString("vlm"),
                    hasil.getString("haktanah")
                });
            }
            tblpopuptanah.setModel(tabmode); // Sesuaikan nama JTable Anda
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tanah gagal dipanggil: " + e);
        }
    }

    // Pemicu Klik Event pada JTable di Pop-up Tanah
    // Klik kanan JTable -> Events -> Mouse -> mouseClicked
    
    // Pemicu Klik pada Tombol Cari di Pop-up
    private void btnCariTanahActionPerformed(java.awt.event.ActionEvent evt) {                                             
        datatable();
    }
    /**
     * Creates new form pupup_tanah
     */
    public popup_tanah(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpopuptanah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bcari.setText("Cari");

        tblpopuptanah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpopuptanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpopuptanahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpopuptanah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpopuptanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpopuptanahMouseClicked
       int baris = tblpopuptanah.getSelectedRow();
    
    String idtnh = tblpopuptanah.getValueAt(baris, 0).toString();
    String lokasi = tblpopuptanah.getValueAt(baris, 1).toString();
    String volume = tblpopuptanah.getValueAt(baris, 2).toString();
    String hak = tblpopuptanah.getValueAt(baris, 3).toString();
    
    // Taktik baru: Deteksi otomatis apakah form utamanya adalah permohonan
    if (formPermohonan instanceof permohonan) {
        permohonan fp = (permohonan) formPermohonan;
        fp.labidtnh.setText(idtnh);
        fp.lablks.setText(lokasi);
        fp.labvlm.setText(volume);
        fp.labhak.setText(hak);
    }
    
    this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_tblpopuptanahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_tanah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_tanah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_tanah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_tanah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                popup_tanah dialog = new popup_tanah(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpopuptanah;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
