/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author SAIF FATIH D
 */
public class popup_admin extends javax.swing.JDialog {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    // Variabel penampung instance class absen
    public absenpetugas fAbsen = null;
    /**
     * Creates new form popup_admin
     */
    public popup_admin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        datatableAdmin();
    }
    
    protected void datatableAdmin() {
        Object[] Baris = {"ID Admin", "Nama Admin", "No. Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        tblpopupadmin.setModel(tabmode);
        try {
            String sql = "SELECT kd_admin, nm_admin, no_telepon FROM admin";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("kd_admin"),
                    hasil.getString("nm_admin"),
                    hasil.getString("no_telepon")
                });
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat admin: " + e.getMessage());
        }
    }   
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpopupadmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        tblpopupadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpopupadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpopupadminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpopupadmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpopupadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpopupadminMouseClicked
        int baris = tblpopupadmin.getSelectedRow();
        
        // Kirim data langsung ke label yang ada di form absen
        if (fAbsen != null) {
        fAbsen.labnip.setText(tblpopupadmin.getValueAt(baris, 0).toString());
        fAbsen.labnama.setText(tblpopupadmin.getValueAt(baris, 1).toString());
        fAbsen.labtelp.setText(tblpopupadmin.getValueAt(baris, 2).toString());
        }
        // Tutup pop-up otomatis setelah memilih
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tblpopupadminMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
    Object[] Baris = {"ID Admin", "Nama Admin", "No. Telepon"};
    tabmode = new DefaultTableModel(null, Baris);
    tblpopupadmin.setModel(tabmode);
    
    try {
        // Mengambil teks dari field pencarian txtcari
        String cariData = txtcari.getText().trim();
        
        // Query SQL untuk mencari data berdasarkan nama admin (nm_admin)
        String sql = "SELECT kd_admin, nm_admin, no_telepon FROM admin WHERE nm_admin LIKE '%" + cariData + "%'";
        
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        // Looping untuk memasukkan hasil pencarian ke dalam tabel
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("kd_admin"),
                hasil.getString("nm_admin"),
                hasil.getString("no_telepon")
            });
        }
        
        // Jika data tidak ditemukan, beri tahu user
        if (tblpopupadmin.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Data admin dengan nama '" + cariData + "' tidak ditemukan.");
            datatableAdmin(); // Memanggil kembali semua data jika pencarian kosong/tidak ketemu
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal melakukan pencarian: " + e.getMessage());
    } // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                popup_admin dialog = new popup_admin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpopupadmin;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
